"""empty message

Revision ID: 891cdad55930
Revises: f0db9ebe926d
Create Date: 2025-06-14 23:36:47.944462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891cdad55930'
down_revision = 'f0db9ebe926d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
